name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install mapeo-settings-builder
        run: npm install -g mapeo-settings-builder

      - name: Run TypeScript type checking
        run: bun tsc --noEmit

      - name: Run tests
        run: bun test

      - name: Run tests with coverage
        run: bun test --coverage

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: comapeo-config-builder-api:test

      - name: Install mapeo-settings-builder
        run: npm install -g mapeo-settings-builder

      - name: Start Docker container
        run: docker run -d -p 3000:3000 --name api-test comapeo-config-builder-api:test

      - name: Wait for container to start
        run: sleep 5

      - name: Health check
        run: |
          response=$(curl -s http://localhost:3000/health)
          if [[ $response == *"\"status\":\"ok\""* ]]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            echo "Response: $response"
            exit 1
          fi

      - name: Stop Docker container
        run: docker stop api-test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: comapeo-config-builder-api:test
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
